### ISSUE TITLE
Runtimeerror

### ISSUE THREAD

**Issue by aihuanhuan0823** [irasin/Pytorch_Adain_from_scratch#1]
F:\arbitrary\Pytorch_Adain_from_scratch-master\Pytorch_Adain_from_scratch-master>python test.py -c f:\arbitrary\Pytorch_Adain_from_scratch-master\Pytorch_Adain_from_scratch-master\content\tree.jpg -s f:\arbitrary\Pytorch_Adain_from_scratch-master\Pytorch_Adain_from_scratch-master\style\news1.jpg
Traceback (most recent call last):
  File "test.py", line 84, in <module>
    main()
  File "test.py", line 64, in main
    res = torch.cat([c_denorm, out_denorm], dim=0)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 459 and 456 in dimension 2 at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensor.cpp:689

content图片
![tree](https://user-images.githubusercontent.com/56620787/66891584-26126100-f01c-11e9-9a3c-15883df55595.jpg)
style图片
![1](https://user-images.githubusercontent.com/56620787/66891607-34f91380-f01c-11e9-900b-86016c446aea.png)

**Comment by irasin** [comment]
您好

代码错误的原因在于下面这句
```
res = torch.cat([c_denorm, out_denorm], dim=0)
```
原因是因为c_denorm, out_denorm的大小不一样，您可以修改代码，改为手动添加pad使两者可以拼接或者分别保存图片来避免error。

**Comment by aihuanhuan0823** [comment]
请教一下该如何分别保存图片呢？我刚刚尝试把content和style图片resize成相同尺寸，还是出现了相同的问题

**Comment by irasin** [comment]
不需要cat就OK了

**Comment by irasin** [comment]
![c_s_style_transfer_demo](https://user-images.githubusercontent.com/25549893/69709146-40be1680-1140-11ea-99a5-0e542c4bcddf.jpg)
已修复test.py
