### ISSUE TITLE
Do you know the effect of scales of inputs?

### ISSUE THREAD

**Issue by mtroym** [irasin/Pytorch_Adain_from_scratch#3]
Hi!

I am really interested in this concept, and I think you are really somebody, I mean expert🕶️.

As you can see some small textures in the dog, and I think bigger textures are greater(look at the style image, cat)
![WechatIMG25_oilpainting_style_transfer_demo](https://user-images.githubusercontent.com/30402475/76147209-dd476b80-60d4-11ea-83f8-1a2e0db73bfc.jpg)

Do you have tried about the scales that affect the final generated images?
![image](https://user-images.githubusercontent.com/30402475/76147263-7080a100-60d5-11ea-9e30-d621836b904d.png)
Like this ⬆️

Thank you so much! I am trying this as well but it may take longer.

**Comment by irasin** [comment]
Hi, @mtroym 

Thank you for your passion for style transfer. However, I am just doing this for fun. Feel free, just enjoy it!

Let's talk about the stroke control. Actually, a lot of elements will affect the size of the stroke in the output image, such as the receptive fields in NNs, the weight of style loss or the size of the input images. The following paper gives an analysis of the factors affecting the stroke size. I think it would be helpful for you.

Stroke Controllable Fast Style Transfer with Adaptive Receptive Fields
https://arxiv.org/pdf/1802.07101.pdf

The effect of stroke control is as below.
![image](https://user-images.githubusercontent.com/25549893/76155694-eff08d80-6132-11ea-98bd-afcd206565ea.png)

If you have any other questions, feel free to let me know, 

Thanks.

**Comment by mtroym** [comment]
Hi!

This paper is excellent! And I found a correspond codebase.

https://github.com/LouieYang/stroke-controllable-fast-style-transfer
I hope it will help people who have the same questions as me.

Thanks!
