### ISSUE TITLE
The pre-trained model can't be download.

### ISSUE THREAD

**Issue by klforeverl** [irasin/Pytorch_Adain_from_scratch#4]
hell,The pre-trained model can't be download.Can you give a model to me? Thank you.

**Comment by irasin** [comment]
Hi, @klforeverl 

The pre-trained model is on the google drive, and I have tested that the link is available now. Please use a VPN if you want to download it.

Thanks.

**Comment by klforeverl** [comment]
> Hi, @klforeverl
> 
> The pre-trained model is on the google drive, and I have tested that the link is available now. Please use a VPN if you want to download it.
> 
> Thanks.

ok ,Thank you.
