### ISSUE TITLE
test

### ISSUE THREAD

**Issue by world2025** [irasin/Pytorch_Adain_from_scratch#6]
hello,thanks for your codes, can you shre your trained model to test my own content images? thank you

**Comment by irasin** [comment]
hi @tkone2018 , you can download the pretrained model from the google drive link in the test section of the README.md.

**Comment by world2025** [comment]
你好，请问风格数据集有百度云盘链接不，我那个kaggle数据集下载不下来，谢谢

**Comment by irasin** [comment]
您好，这个链接我没有，你可以去搜一搜

**Comment by world2025** [comment]
@irasin 好的，感谢分享的资源
