### ISSUE TITLE
About unpaired image-to-image translation using AdaIN

### ISSUE THREAD

**Issue by jetitime** [irasin/Pytorch_Adain_from_scratch#9]
Hi @irasin , I am very interested in this image-to-image translation translation without Cycle Consistency Loss. I am confused about wether this method can be used in unpaired image-to-image? I think maybe can achieve it by changing datasets.py.

**Comment by irasin** [comment]
Hi, @jetitime, I' m not sure what is the your task about  unpaired image-to-image, but AdaIN is trained with unpaired content and style images, it may work in your task too.
